# Simple LSTM

In [1]:
import whiteboxlayer.layers as wbl
import whiteboxlayer.extensions.recurrent as recurrent
import tensorflow as tf

class Neuralnet(tf.Module):

    def __init__(self, **kwargs):
        super(Neuralnet, self).__init__()

        self.who_am_i = kwargs['who_am_i']
        self.dim_seq = kwargs['dim_seq']
        self.dim_dim = kwargs['dim_dim']
        self.filters = kwargs['filters']
        print(self.filters)

        self.layer = wbl.Layers()

        self.forward = tf.function(self.__call__)

    @tf.function
    def __call__(self, x, verbose=False):

        logit = self.__nn(x=x, name=self.who_am_i, verbose=verbose)
        y_hat = tf.nn.softmax(logit, name="y_hat")

        return logit, y_hat

    def __nn(self, x, name='neuralnet', verbose=True):
        
        for idx_f, _ in enumerate(self.filters):
            if(idx_f == 0): continue
            
            x = recurrent.lstm_layer(layer=self.layer, x=x, output_len=self.filters[idx_f], \
                batch_norm=False, activation="tanh", recurrent_activation="sigmoid", \
                name='%s-%d_lstm' %(name, idx_f), verbose=True)
        
        return x


In [2]:
model = Neuralnet(\
    who_am_i="LSTM", \
    dim_seq=32, dim_dim=128, \
    filters=[128, 64, 128])

dummy = tf.zeros((1, model.dim_seq, model.dim_dim), dtype=tf.float32)
model.forward(x=dummy, verbose=True)

ListWrapper([128, 64, 128])
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
FC (LSTM-1_lstm-i-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-i-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-i-term2) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-i) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-f-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-f-term2) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-f) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-o-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-o-term2) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-o) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-c-term1_1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-c-term2_1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-y) (1, 128) -> (1, 64)
LSTM Cell (LSTM-1_lstm) (1, 128) -> (1, 64)
FC (LSTM-2_lstm-i-term1) (1, 64) -> (1, 64)
FC (LSTM-2_lstm-i-term1) (1, 64) 

(<tf.Tensor: shape=(1, 32, 128), dtype=float32, numpy=
 array([[[ 0.17216732, -0.05660438, -0.05652115, ...,  0.00614765,
          -0.19075756,  0.01638486],
         [ 0.16547108, -0.07944618, -0.03668876, ..., -0.02364307,
          -0.2000076 , -0.01552578],
         [ 0.15563273, -0.08830049, -0.01672306, ..., -0.0405835 ,
          -0.21054931, -0.02818621],
         ...,
         [ 0.1397443 , -0.09616747,  0.01645362, ..., -0.06326864,
          -0.23011462, -0.05624092],
         [ 0.13974923, -0.09616017,  0.01646883, ..., -0.06327075,
          -0.23011582, -0.0562383 ],
         [ 0.1397527 , -0.09615446,  0.01648041, ..., -0.06327148,
          -0.23011692, -0.05623574]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 32, 128), dtype=float32, numpy=
 array([[[0.00922493, 0.00733853, 0.00733914, ..., 0.00781379,
          0.00641722, 0.00789419],
         [0.00913522, 0.00715077, 0.00746315, ..., 0.00756115,
          0.00633861, 0.00762278],
         [0.00903114, 0.00707626, 0.0

# Simple LSTM with Batch Normalization

In [3]:
import whiteboxlayer.layers as wbl
import whiteboxlayer.extensions.recurrent as recurrent
import tensorflow as tf

class Neuralnet(tf.Module):

    def __init__(self, **kwargs):
        super(Neuralnet, self).__init__()

        self.who_am_i = kwargs['who_am_i']
        self.dim_seq = kwargs['dim_seq']
        self.dim_dim = kwargs['dim_dim']
        self.filters = kwargs['filters']
        print(self.filters)

        self.layer = wbl.Layers()

        self.forward = tf.function(self.__call__)

    @tf.function
    def __call__(self, x, verbose=False):

        logit = self.__nn(x=x, name=self.who_am_i, verbose=verbose)
        y_hat = tf.nn.softmax(logit, name="y_hat")

        return logit, y_hat

    def __nn(self, x, name='neuralnet', verbose=True):
        
        for idx_f, _ in enumerate(self.filters):
            if(idx_f == 0): continue
            
            x = recurrent.lstm_layer(layer=self.layer, x=x, output_len=self.filters[idx_f], \
                batch_norm=True, activation="tanh", recurrent_activation="sigmoid", \
                name='%s-%d_lstm' %(name, idx_f), verbose=True)
        
        return x


In [4]:
model = Neuralnet(\
    who_am_i="LSTM", \
    dim_seq=32, dim_dim=128, \
    filters=[128, 64, 128])

dummy = tf.zeros((1, model.dim_seq, model.dim_dim), dtype=tf.float32)
model.forward(x=dummy, verbose=True)

ListWrapper([128, 64, 128])
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
FC (LSTM-1_lstm-i-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-i-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-i-term2) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-i) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-f-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-f-term2) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-f) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-o-term1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-o-term2) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-o) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-c-term1_1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-c-term2_1) (1, 128) -> (1, 128)
FC (LSTM-1_lstm-y) (1, 128) -> (1, 64)
LSTM Cell (LSTM-1_lstm) (1, 128) -> (1, 64)
BN (LSTM-1_lstm_bn) (1, 32, 64) -> (1, 32, 64)
FC (LSTM-2_lstm-i-term1) (1, 6

(<tf.Tensor: shape=(1, 32, 128), dtype=float32, numpy=
 array([[[-0.01889078,  0.27042472,  0.6639321 , ..., -1.1826555 ,
           0.17029546,  1.0223644 ],
         [ 0.13506773,  0.5119995 ,  1.0643611 , ..., -1.3282772 ,
           0.33201495,  1.034781  ],
         [ 0.32024765,  0.6076434 ,  1.2666408 , ..., -1.2982372 ,
           0.394668  ,  0.91214055],
         ...,
         [ 0.45947433,  0.15619189,  1.8693663 , ..., -1.5289683 ,
           0.8086788 , -0.27256197],
         [ 0.45928925,  0.15548977,  1.8697177 , ..., -1.5300493 ,
           0.8086405 , -0.27177668],
         [ 0.45913765,  0.15489802,  1.8700079 , ..., -1.5310099 ,
           0.8085939 , -0.2710569 ]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 32, 128), dtype=float32, numpy=
 array([[[0.00587615, 0.00784768, 0.01163159, ..., 0.00183517,
          0.00709995, 0.01664579],
         [0.00605753, 0.0088307 , 0.01534202, ..., 0.00140208,
          0.00737613, 0.01489485],
         [0.00688807, 0.00918146, 0.0